fix int queries
owncloud/ocis-glauth pull request #29
Opened 2020-07-24 16:25 UTC by butonic

- [ ] changelog

2020-07-25 03:36 UTC, kulmann approved these changes

2020-07-27 08:07 UTC, refs requested changes

2020-07-27 08:07 UTC, refs commented on pkg/server/glauth/handler.go
> +			q = fmt.Sprintf("uid_number eq %s", value) // TODO check it is a number?
That todo can potentially come back in the future and bite us. Why not addressing it here? [There's this](https://golang.org/pkg/strconv/#ParseInt)

2020-07-27 09:01 UTC, refs approved these changes

2020-07-27 09:31 UTC, merged